<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="KanvasBuddy">
    <Actions category="Scripts">
        <text>KanvasBuddy</text>

        <Action name="kanvasbuddy">
        <icon></icon>
        <text>Launch KanvasBuddy</text>
        <whatsThis>Minimalist toolbar for Krita</whatsThis>
        <toolTip>Minimalist toolbar for Krita</toolTip>
        <iconText>KB</iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+k</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>